[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]
via_ir = true

[rpc_endpoints]
mainnet = "${ETHERLINK_MAINNET_RPC_URL}"
testnet = "${ETHERLINK_TESTNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 32
fail_on_revert = true
